### ISSUE TITLE
Support loading 1.13+ ItemStacks stored YAML on 1.12.2 and before

### ISSUE THREAD

**Issue by bergerkiller** [bergerhealer/BKCommonLib#85]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug:
Loading YAML containing ItemStack information saved on MC 1.13 or later, on MC 1.12.2, does not function in all expected cases

#### Expected behaviour:
Can load YAML containing itemstacks saved on later versions

#### Steps to reproduce:
Attempt loading YAML such as:
```
item:
  ==: org.bukkit.inventory.ItemStack
  type: BIRCH_LEAVES
  damage: 3
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    Unbreakable: true
```
Which fails to find the material 'BIRCH_LEAVES'  (called 'LEAVES' on 1.12.2)
